Fixed http status checking
wizzdev-pl/iot-starter pull request #4
Opened 2021-02-15 15:05 UTC by piotr-kwiatkowski-wizzdev

2021-02-16 13:22 UTC, wizzdev-pl requested changes

2021-02-16 13:22 UTC, wizzdev-pl commented on MicroPython/src/communication/API_communication.py
> +    if response.status_code != '200': #and response.status_code != 200:
I do not understand the comment. Additionally please use two spaces before comments and one after the hash e.g.:
if response.status_code != '200':  # my comment

2021-02-17 14:19 UTC, marcin-nawrocki-wizzdev approved these changes

2021-02-17 21:35 UTC, wizzdev-pl approved these changes

2021-02-17 21:36 UTC, merged